version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo Install phase - no dependencies to install
  build:
    commands:
      - echo Zipping Lambda functions...
      # If your handler is set to "produce_data.lambda_handler"
      - zip -j $PRODUCE_FUNCTION_NAME.zip app/produce_data.py
      - zip -j $PROCESS_FUNCTION_NAME.zip app/process_filtered_data.py
      - zip -j $ENRICH_FUNCTION_NAME.zip app/enrich_data.py
      - echo Uploading zips to S3...
      - aws s3 cp $PRODUCE_FUNCTION_NAME.zip s3://$DEPLOY_BUCKET/
      - aws s3 cp $PROCESS_FUNCTION_NAME.zip s3://$DEPLOY_BUCKET/
      - aws s3 cp $ENRICH_FUNCTION_NAME.zip s3://$DEPLOY_BUCKET/
  post_build:
    commands:
      - echo Updating Lambda function code...
      - aws lambda update-function-code --function-name $PRODUCE_FUNCTION_NAME --s3-bucket $DEPLOY_BUCKET --s3-key $PRODUCE_FUNCTION_NAME.zip --region us-east-1
      - aws lambda update-function-code --function-name $PROCESS_FUNCTION_NAME --s3-bucket $DEPLOY_BUCKET --s3-key $PROCESS_FUNCTION_NAME.zip --region us-east-1
      - aws lambda update-function-code --function-name $ENRICH_FUNCTION_NAME --s3-bucket $DEPLOY_BUCKET --s3-key $ENRICH_FUNCTION_NAME.zip --region us-east-1
      - echo Updating environment variables on Lambda...
      - aws lambda update-function-configuration --function-name $PRODUCE_FUNCTION_NAME --environment "Variables={QUEUE_URL=$QUEUE_URL}" --region us-east-1
      - aws lambda update-function-configuration --function-name $PROCESS_FUNCTION_NAME --environment "Variables={TARGET_BUCKET=$TARGET_BUCKET}" --region us-east-1
      - echo Waiting for configuration update to complete...
      - sleep 15
      - echo Checking Lambda handler configuration...
      - aws lambda get-function-configuration --function-name $PRODUCE_FUNCTION_NAME --region us-east-1 --query Handler
      - echo Setting correct handler...
      - aws lambda update-function-configuration --function-name $PRODUCE_FUNCTION_NAME --handler produce_data.lambda_handler --region us-east-1
      - echo Waiting for handler update...
      - sleep 10
      - echo Invoking Producer Lambda...
      - aws lambda invoke --function-name $PRODUCE_FUNCTION_NAME --invocation-type Event --region us-east-1 --payload '{}' response.json
      - echo Checking invocation response...
      - cat response.json

artifacts:
  files:
    - "**/*"
